"use client";

import { useEffect } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Playfair_Display } from 'next/font/google'

import { ParallaxProvider } from "react-scroll-parallax";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '600'],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  useEffect(() => {
    const tgWebApp = (window as Window & { Telegram?: { WebApp?: { disableVerticalSwipes?: () => void; enableVerticalSwipes?: () => void } } }).Telegram?.WebApp;
    const isTelegramWebView = Boolean(tgWebApp);

    if (isTelegramWebView) {
      tgWebApp?.disableVerticalSwipes?.();
    }

    document.documentElement.classList.toggle("tg-webview", isTelegramWebView);
    document.body.classList.toggle("tg-webview", isTelegramWebView);

    return () => {
      tgWebApp?.enableVerticalSwipes?.();
      document.documentElement.classList.remove("tg-webview");
      document.body.classList.remove("tg-webview");
    };
  }, []);

  return (
    <html lang="en">
      <body
        className={`${playfair.className} antialiased`}
      >
        <ParallaxProvider>
          {children}
        </ParallaxProvider>
      </body>
    </html>
  );
}
